apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tacocat
    service: packaging
    shard: blue
  name: packaging-blue
  namespace: tacocat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tacocat
      service: packaging
      shard: blue
  template:
    metadata:
      labels:
        app: tacocat
        service: packaging
        shard: blue
    spec:
      containers:
      - name: packaging
        image: dambott/x64packaging:latest
        imagePullPolicy: Always
        command:
        - "java"
        - "-javaagent:opentelemetry-javaagent.jar"
        - "-Dotel.javaagent.configuration-file=/otel/packaging.blue.properties"
        - "-jar"
        - "/packaging.jar"
        - "/conf/packaging-app.yaml"
        ports:
        - containerPort: 50053
          name: application
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
        - name: otel
          mountPath: /otel
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 350Mi
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
      - name: otel
        configMap:
          name: otel-config
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tacocat
    service: packaging
    shard: green
  name: packaging-green
  namespace: tacocat
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tacocat
      service: packaging
      shard: green
  template:
    metadata:
      labels:
        app: tacocat
        service: packaging
        shard: green
    spec:
      containers:
        - name: packaging
          image: dambott/x64packaging:latest
          imagePullPolicy: Always
          command:
            - "java"
            - "-javaagent:opentelemetry-javaagent.jar"
            - "-Dotel.javaagent.configuration-file=/otel/packaging.green.properties"
            - "-jar"
            - "/packaging.jar"
            - "/conf/packaging-app.yaml"
          ports:
            - containerPort: 50053
              name: application
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
            - name: otel
              mountPath: /otel
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 350Mi
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744
        - name: otel
          configMap:
            name: otel-config
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: packaging
  namespace: tacocat
spec: 
  selector:
    app: tacocat
    service: packaging
  type: ClusterIP
  ports:
  - name: application
    port: 50053

