apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tacocat
    service: delivery
    shard: blue
  name: delivery-blue
  namespace: tacocat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tacocat
      service: delivery
      shard: blue
  template:
    metadata:
      labels:
        app: tacocat
        service: delivery
        shard: blue
    spec:
      containers:
      - name: delivery
        image: dambott/x64delivery:latest
        imagePullPolicy: Always
        command:
        - "java"
        - "-javaagent:opentelemetry-javaagent.jar"
        - "-Dotel.javaagent.configuration-file=/otel/delivery.blue.properties"
        - "-jar"
        - "/delivery.jar"
        - "--spring.config.location=/conf/delivery-app.yml"
        ports:
        - containerPort: 50054
          name: application
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
        - name: otel
          mountPath: /otel
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 350Mi
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
      - name: otel
        configMap:
          name: otel-config
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tacocat
    service: delivery
    shard: green
  name: delivery-green
  namespace: tacocat
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tacocat
      service: delivery
      shard: green
  template:
    metadata:
      labels:
        app: tacocat
        service: delivery
        shard: green
    spec:
      containers:
        - name: delivery
          image: dambott/x64delivery:latest
          imagePullPolicy: Always
          command:
            - "java"
            - "-javaagent:opentelemetry-javaagent.jar"
            - "-Dotel.javaagent.configuration-file=/otel/delivery.green.properties"
            - "-jar"
            - "/delivery.jar"
            - "--spring.config.location=/conf/delivery-app.yml"
          ports:
            - containerPort: 50054
              name: application
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
            - name: otel
              mountPath: /otel
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 350Mi
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744
        - name: otel
          configMap:
            name: otel-config
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: delivery
  namespace: tacocat
spec: 
  selector:
    app: tacocat
    service: delivery  
  type: ClusterIP
  ports:
  - name: application
    port: 50054

